# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: admin.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'admin.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61\x64min.proto\x12\x05\x61\x64min\"\x1a\n\x18GetDashboardStatsRequest\"\x89\x01\n\x16\x44\x61shboardStatsResponse\x12\x14\n\x0c\x65vents_today\x18\x01 \x01(\x05\x12\x14\n\x0c\x64\x65nied_today\x18\x02 \x01(\x05\x12\x15\n\ractive_tokens\x18\x03 \x01(\x05\x12\x16\n\x0e\x61\x63tive_dongles\x18\x04 \x01(\x05\x12\x14\n\x0c\x61\x63tive_hosts\x18\x05 \x01(\x05\"Q\n\x10GetEventsRequest\x12\r\n\x05limit\x18\x01 \x01(\x05\x12\x0e\n\x06offset\x18\x02 \x01(\x05\x12\x10\n\x08severity\x18\x03 \x01(\t\x12\x0c\n\x04host\x18\x04 \x01(\t\"\x97\x01\n\x05\x45vent\x12\x11\n\ttimestamp\x18\x01 \x01(\t\x12\x0c\n\x04host\x18\x02 \x01(\t\x12\x12\n\nevent_type\x18\x03 \x01(\t\x12\x10\n\x08severity\x18\x04 \x01(\t\x12\x11\n\tfile_path\x18\x05 \x01(\t\x12\x0f\n\x07user_id\x18\x06 \x01(\t\x12\x0e\n\x06result\x18\x07 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x08 \x01(\t\"@\n\x11GetEventsResponse\x12\x1c\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x0c.admin.Event\x12\r\n\x05total\x18\x02 \x01(\x05\"*\n\x13UpdatePolicyRequest\x12\x13\n\x0bpolicy_yaml\x18\x01 \x01(\t\"G\n\x14UpdatePolicyResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t2\xec\x01\n\x0c\x41\x64minService\x12S\n\x11GetDashboardStats\x12\x1f.admin.GetDashboardStatsRequest\x1a\x1d.admin.DashboardStatsResponse\x12>\n\tGetEvents\x12\x17.admin.GetEventsRequest\x1a\x18.admin.GetEventsResponse\x12G\n\x0cUpdatePolicy\x12\x1a.admin.UpdatePolicyRequest\x1a\x1b.admin.UpdatePolicyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'admin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETDASHBOARDSTATSREQUEST']._serialized_start=22
  _globals['_GETDASHBOARDSTATSREQUEST']._serialized_end=48
  _globals['_DASHBOARDSTATSRESPONSE']._serialized_start=51
  _globals['_DASHBOARDSTATSRESPONSE']._serialized_end=188
  _globals['_GETEVENTSREQUEST']._serialized_start=190
  _globals['_GETEVENTSREQUEST']._serialized_end=271
  _globals['_EVENT']._serialized_start=274
  _globals['_EVENT']._serialized_end=425
  _globals['_GETEVENTSRESPONSE']._serialized_start=427
  _globals['_GETEVENTSRESPONSE']._serialized_end=491
  _globals['_UPDATEPOLICYREQUEST']._serialized_start=493
  _globals['_UPDATEPOLICYREQUEST']._serialized_end=535
  _globals['_UPDATEPOLICYRESPONSE']._serialized_start=537
  _globals['_UPDATEPOLICYRESPONSE']._serialized_end=608
  _globals['_ADMINSERVICE']._serialized_start=611
  _globals['_ADMINSERVICE']._serialized_end=847
# @@protoc_insertion_point(module_scope)
